x-network:
  links:
    - {service: api, bridge: ctrl, dev: eth0, ip: 10.0.0.1/16}

services:
  api:
    scale: 3

  static-config:
    image: ubuntu:24.04
    volumes:
      - state:/state
    command: bash -c 'mkdir /state/servers && echo -e "  server server1  10.0.0.1:8000\n  server server2  10.0.0.2:8000\n  server server3  10.0.0.3:8000" > /state/servers/static.cfg'
