x-network:
  links:
    - {service: api, bridge: ctrl, dev: ctl0, ip: 10.0.0.1/16}
    - {service: db,  bridge: ctrl, dev: ctl0, ip: 10.0.1.1/16}

x-extra-hosts: &extra-hosts
  - db:      "10.0.1.1"

services:
  api:
    build: {context: ./app}
    scale: 1
    network_mode: none
    extra_hosts: { <<: *extra-hosts }
    command: node /app/index.js ext0

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: demo
      #POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./conlink/scripts:/scripts:ro
      - ./.files/db:/files:ro
    network_mode: none  # port 5432
    entrypoint: /scripts/copy.sh /files / -- docker-entrypoint.sh
    command: postgres
